// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file ET.proto (package et, syntax proto2)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ET.proto.
 */
export const file_ET: GenFile = /*@__PURE__*/
  fileDesc("CghFVC5wcm90bxICZXQiMwoOQ29ubmVjdFJlcXVlc3QSEAoIY2xpZW50SWQYASABKAkSDwoHdmVyc2lvbhgCIAEoBSJDCg9Db25uZWN0UmVzcG9uc2USIQoGc3RhdHVzGAEgASgOMhEuZXQuQ29ubmVjdFN0YXR1cxINCgVlcnJvchgCIAEoCSIoCg5TZXF1ZW5jZUhlYWRlchIWCg5zZXF1ZW5jZU51bWJlchgBIAEoBSIfCg1DYXRjaHVwQnVmZmVyEg4KBmJ1ZmZlchgBIAMoDCIsCg5Tb2NrZXRFbmRwb2ludBIMCgRuYW1lGAEgASgJEgwKBHBvcnQYAiABKAUqSwoMRXRQYWNrZXRUeXBlEg4KCUhFQVJUQkVBVBD+ARIUCg9JTklUSUFMX1BBWUxPQUQQ/QESFQoQSU5JVElBTF9SRVNQT05TRRD8ASpfCg1Db25uZWN0U3RhdHVzEg4KCk5FV19DTElFTlQQARIUChBSRVRVUk5JTkdfQ0xJRU5UEAISDwoLSU5WQUxJRF9LRVkQAxIXChNNSVNNQVRDSEVEX1BST1RPQ09MEARCAkgD");

/**
 * @generated from message et.ConnectRequest
 */
export type ConnectRequest = Message<"et.ConnectRequest"> & {
  /**
   * @generated from field: optional string clientId = 1;
   */
  clientId: string;

  /**
   * @generated from field: optional int32 version = 2;
   */
  version: number;
};

/**
 * Describes the message et.ConnectRequest.
 * Use `create(ConnectRequestSchema)` to create a new message.
 */
export const ConnectRequestSchema: GenMessage<ConnectRequest> = /*@__PURE__*/
  messageDesc(file_ET, 0);

/**
 * @generated from message et.ConnectResponse
 */
export type ConnectResponse = Message<"et.ConnectResponse"> & {
  /**
   * @generated from field: optional et.ConnectStatus status = 1;
   */
  status: ConnectStatus;

  /**
   * @generated from field: optional string error = 2;
   */
  error: string;
};

/**
 * Describes the message et.ConnectResponse.
 * Use `create(ConnectResponseSchema)` to create a new message.
 */
export const ConnectResponseSchema: GenMessage<ConnectResponse> = /*@__PURE__*/
  messageDesc(file_ET, 1);

/**
 * @generated from message et.SequenceHeader
 */
export type SequenceHeader = Message<"et.SequenceHeader"> & {
  /**
   * @generated from field: optional int32 sequenceNumber = 1;
   */
  sequenceNumber: number;
};

/**
 * Describes the message et.SequenceHeader.
 * Use `create(SequenceHeaderSchema)` to create a new message.
 */
export const SequenceHeaderSchema: GenMessage<SequenceHeader> = /*@__PURE__*/
  messageDesc(file_ET, 2);

/**
 * @generated from message et.CatchupBuffer
 */
export type CatchupBuffer = Message<"et.CatchupBuffer"> & {
  /**
   * @generated from field: repeated bytes buffer = 1;
   */
  buffer: Uint8Array[];
};

/**
 * Describes the message et.CatchupBuffer.
 * Use `create(CatchupBufferSchema)` to create a new message.
 */
export const CatchupBufferSchema: GenMessage<CatchupBuffer> = /*@__PURE__*/
  messageDesc(file_ET, 3);

/**
 * @generated from message et.SocketEndpoint
 */
export type SocketEndpoint = Message<"et.SocketEndpoint"> & {
  /**
   * @generated from field: optional string name = 1;
   */
  name: string;

  /**
   * @generated from field: optional int32 port = 2;
   */
  port: number;
};

/**
 * Describes the message et.SocketEndpoint.
 * Use `create(SocketEndpointSchema)` to create a new message.
 */
export const SocketEndpointSchema: GenMessage<SocketEndpoint> = /*@__PURE__*/
  messageDesc(file_ET, 4);

/**
 * @generated from enum et.EtPacketType
 */
export enum EtPacketType {
  /**
   * Count down from 254 to avoid collisions
   *
   * @generated from enum value: HEARTBEAT = 254;
   */
  HEARTBEAT = 254,

  /**
   * @generated from enum value: INITIAL_PAYLOAD = 253;
   */
  INITIAL_PAYLOAD = 253,

  /**
   * @generated from enum value: INITIAL_RESPONSE = 252;
   */
  INITIAL_RESPONSE = 252,
}

/**
 * Describes the enum et.EtPacketType.
 */
export const EtPacketTypeSchema: GenEnum<EtPacketType> = /*@__PURE__*/
  enumDesc(file_ET, 0);

/**
 * @generated from enum et.ConnectStatus
 */
export enum ConnectStatus {
  /**
   * @generated from enum value: NEW_CLIENT = 1;
   */
  NEW_CLIENT = 1,

  /**
   * @generated from enum value: RETURNING_CLIENT = 2;
   */
  RETURNING_CLIENT = 2,

  /**
   * @generated from enum value: INVALID_KEY = 3;
   */
  INVALID_KEY = 3,

  /**
   * @generated from enum value: MISMATCHED_PROTOCOL = 4;
   */
  MISMATCHED_PROTOCOL = 4,
}

/**
 * Describes the enum et.ConnectStatus.
 */
export const ConnectStatusSchema: GenEnum<ConnectStatus> = /*@__PURE__*/
  enumDesc(file_ET, 1);
