// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file ETerminal.proto (package et, syntax proto2)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { SocketEndpoint } from "./ET_pb";
import { file_ET } from "./ET_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ETerminal.proto.
 */
export const file_ETerminal: GenFile = /*@__PURE__*/
  fileDesc("Cg9FVGVybWluYWwucHJvdG8SAmV0IiAKDlRlcm1pbmFsQnVmZmVyEg4KBmJ1ZmZlchgBIAEoDCJWCgxUZXJtaW5hbEluZm8SCgoCaWQYASABKAkSCwoDcm93GAIgASgFEg4KBmNvbHVtbhgDIAEoBRINCgV3aWR0aBgEIAEoBRIOCgZoZWlnaHQYBSABKAUihAEKGFBvcnRGb3J3YXJkU291cmNlUmVxdWVzdBIiCgZzb3VyY2UYASABKAsyEi5ldC5Tb2NrZXRFbmRwb2ludBInCgtkZXN0aW5hdGlvbhgCIAEoCzISLmV0LlNvY2tldEVuZHBvaW50EhsKE2Vudmlyb25tZW50dmFyaWFibGUYAyABKAkiKgoZUG9ydEZvcndhcmRTb3VyY2VSZXNwb25zZRINCgVlcnJvchgBIAEoCSJUCh1Qb3J0Rm9yd2FyZERlc3RpbmF0aW9uUmVxdWVzdBInCgtkZXN0aW5hdGlvbhgBIAEoCzISLmV0LlNvY2tldEVuZHBvaW50EgoKAmZkGAIgASgFIlMKHlBvcnRGb3J3YXJkRGVzdGluYXRpb25SZXNwb25zZRIQCghjbGllbnRmZBgBIAEoBRIQCghzb2NrZXRpZBgCIAEoBRINCgVlcnJvchgDIAEoCSJvCg9Qb3J0Rm9yd2FyZERhdGESGwoTc291cmNldG9kZXN0aW5hdGlvbhgBIAEoCBIQCghzb2NrZXRpZBgCIAEoBRIOCgZidWZmZXIYAyABKAwSDQoFZXJyb3IYBCABKAkSDgoGY2xvc2VkGAUgASgIIugBCg5Jbml0aWFsUGF5bG9hZBIXCghqdW1waG9zdBgBIAEoCDoFZmFsc2USNAoOcmV2ZXJzZXR1bm5lbHMYAiADKAsyHC5ldC5Qb3J0Rm9yd2FyZFNvdXJjZVJlcXVlc3QSSgoUZW52aXJvbm1lbnR2YXJpYWJsZXMYAyADKAsyLC5ldC5Jbml0aWFsUGF5bG9hZC5FbnZpcm9ubWVudHZhcmlhYmxlc0VudHJ5GjsKGUVudmlyb25tZW50dmFyaWFibGVzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASIgCg9Jbml0aWFsUmVzcG9uc2USDQoFZXJyb3IYASABKAkiMwoMQ29uZmlnUGFyYW1zEg4KBnZsZXZlbBgBIAEoBRITCgttaW5sb2dsZXZlbBgCIAEoBSI/CghUZXJtSW5pdBIYChBlbnZpcm9ubWVudG5hbWVzGAEgAygJEhkKEWVudmlyb25tZW50dmFsdWVzGAIgAygJIlUKEFRlcm1pbmFsVXNlckluZm8SCgoCaWQYASABKAkSDwoHcGFzc2tleRgCIAEoCRILCgN1aWQYAyABKAMSCwoDZ2lkGAQgASgDEgoKAmZkGAUgASgDKu4BChJUZXJtaW5hbFBhY2tldFR5cGUSDgoKS0VFUF9BTElWRRAAEhMKD1RFUk1JTkFMX0JVRkZFUhABEhEKDVRFUk1JTkFMX0lORk8QAhIkCiBQT1JUX0ZPUldBUkRfREVTVElOQVRJT05fUkVRVUVTVBAFEiUKIVBPUlRfRk9SV0FSRF9ERVNUSU5BVElPTl9SRVNQT05TRRAGEhUKEVBPUlRfRk9SV0FSRF9EQVRBEAcSFgoSVEVSTUlOQUxfVVNFUl9JTkZPEAgSEQoNVEVSTUlOQUxfSU5JVBAJEhEKDUpVTVBIT1NUX0lOSVQQCkICSAM", [file_ET]);

/**
 * @generated from message et.TerminalBuffer
 */
export type TerminalBuffer = Message<"et.TerminalBuffer"> & {
  /**
   * @generated from field: optional bytes buffer = 1;
   */
  buffer: Uint8Array;
};

/**
 * Describes the message et.TerminalBuffer.
 * Use `create(TerminalBufferSchema)` to create a new message.
 */
export const TerminalBufferSchema: GenMessage<TerminalBuffer> = /*@__PURE__*/
  messageDesc(file_ETerminal, 0);

/**
 * @generated from message et.TerminalInfo
 */
export type TerminalInfo = Message<"et.TerminalInfo"> & {
  /**
   * @generated from field: optional string id = 1;
   */
  id: string;

  /**
   * @generated from field: optional int32 row = 2;
   */
  row: number;

  /**
   * @generated from field: optional int32 column = 3;
   */
  column: number;

  /**
   * @generated from field: optional int32 width = 4;
   */
  width: number;

  /**
   * @generated from field: optional int32 height = 5;
   */
  height: number;
};

/**
 * Describes the message et.TerminalInfo.
 * Use `create(TerminalInfoSchema)` to create a new message.
 */
export const TerminalInfoSchema: GenMessage<TerminalInfo> = /*@__PURE__*/
  messageDesc(file_ETerminal, 1);

/**
 * @generated from message et.PortForwardSourceRequest
 */
export type PortForwardSourceRequest = Message<"et.PortForwardSourceRequest"> & {
  /**
   * @generated from field: optional et.SocketEndpoint source = 1;
   */
  source?: SocketEndpoint | undefined;

  /**
   * @generated from field: optional et.SocketEndpoint destination = 2;
   */
  destination?: SocketEndpoint | undefined;

  /**
   * @generated from field: optional string environmentvariable = 3;
   */
  environmentvariable: string;
};

/**
 * Describes the message et.PortForwardSourceRequest.
 * Use `create(PortForwardSourceRequestSchema)` to create a new message.
 */
export const PortForwardSourceRequestSchema: GenMessage<PortForwardSourceRequest> = /*@__PURE__*/
  messageDesc(file_ETerminal, 2);

/**
 * @generated from message et.PortForwardSourceResponse
 */
export type PortForwardSourceResponse = Message<"et.PortForwardSourceResponse"> & {
  /**
   * @generated from field: optional string error = 1;
   */
  error: string;
};

/**
 * Describes the message et.PortForwardSourceResponse.
 * Use `create(PortForwardSourceResponseSchema)` to create a new message.
 */
export const PortForwardSourceResponseSchema: GenMessage<PortForwardSourceResponse> = /*@__PURE__*/
  messageDesc(file_ETerminal, 3);

/**
 * @generated from message et.PortForwardDestinationRequest
 */
export type PortForwardDestinationRequest = Message<"et.PortForwardDestinationRequest"> & {
  /**
   * @generated from field: optional et.SocketEndpoint destination = 1;
   */
  destination?: SocketEndpoint | undefined;

  /**
   * @generated from field: optional int32 fd = 2;
   */
  fd: number;
};

/**
 * Describes the message et.PortForwardDestinationRequest.
 * Use `create(PortForwardDestinationRequestSchema)` to create a new message.
 */
export const PortForwardDestinationRequestSchema: GenMessage<PortForwardDestinationRequest> = /*@__PURE__*/
  messageDesc(file_ETerminal, 4);

/**
 * @generated from message et.PortForwardDestinationResponse
 */
export type PortForwardDestinationResponse = Message<"et.PortForwardDestinationResponse"> & {
  /**
   * @generated from field: optional int32 clientfd = 1;
   */
  clientfd: number;

  /**
   * @generated from field: optional int32 socketid = 2;
   */
  socketid: number;

  /**
   * @generated from field: optional string error = 3;
   */
  error: string;
};

/**
 * Describes the message et.PortForwardDestinationResponse.
 * Use `create(PortForwardDestinationResponseSchema)` to create a new message.
 */
export const PortForwardDestinationResponseSchema: GenMessage<PortForwardDestinationResponse> = /*@__PURE__*/
  messageDesc(file_ETerminal, 5);

/**
 * @generated from message et.PortForwardData
 */
export type PortForwardData = Message<"et.PortForwardData"> & {
  /**
   * @generated from field: optional bool sourcetodestination = 1;
   */
  sourcetodestination: boolean;

  /**
   * @generated from field: optional int32 socketid = 2;
   */
  socketid: number;

  /**
   * @generated from field: optional bytes buffer = 3;
   */
  buffer: Uint8Array;

  /**
   * @generated from field: optional string error = 4;
   */
  error: string;

  /**
   * @generated from field: optional bool closed = 5;
   */
  closed: boolean;
};

/**
 * Describes the message et.PortForwardData.
 * Use `create(PortForwardDataSchema)` to create a new message.
 */
export const PortForwardDataSchema: GenMessage<PortForwardData> = /*@__PURE__*/
  messageDesc(file_ETerminal, 6);

/**
 * @generated from message et.InitialPayload
 */
export type InitialPayload = Message<"et.InitialPayload"> & {
  /**
   * @generated from field: optional bool jumphost = 1 [default = false];
   */
  jumphost: boolean;

  /**
   * @generated from field: repeated et.PortForwardSourceRequest reversetunnels = 2;
   */
  reversetunnels: PortForwardSourceRequest[];

  /**
   * @generated from field: map<string, string> environmentvariables = 3;
   */
  environmentvariables: { [key: string]: string };
};

/**
 * Describes the message et.InitialPayload.
 * Use `create(InitialPayloadSchema)` to create a new message.
 */
export const InitialPayloadSchema: GenMessage<InitialPayload> = /*@__PURE__*/
  messageDesc(file_ETerminal, 7);

/**
 * @generated from message et.InitialResponse
 */
export type InitialResponse = Message<"et.InitialResponse"> & {
  /**
   * @generated from field: optional string error = 1;
   */
  error: string;
};

/**
 * Describes the message et.InitialResponse.
 * Use `create(InitialResponseSchema)` to create a new message.
 */
export const InitialResponseSchema: GenMessage<InitialResponse> = /*@__PURE__*/
  messageDesc(file_ETerminal, 8);

/**
 * @generated from message et.ConfigParams
 */
export type ConfigParams = Message<"et.ConfigParams"> & {
  /**
   * @generated from field: optional int32 vlevel = 1;
   */
  vlevel: number;

  /**
   * @generated from field: optional int32 minloglevel = 2;
   */
  minloglevel: number;
};

/**
 * Describes the message et.ConfigParams.
 * Use `create(ConfigParamsSchema)` to create a new message.
 */
export const ConfigParamsSchema: GenMessage<ConfigParams> = /*@__PURE__*/
  messageDesc(file_ETerminal, 9);

/**
 * @generated from message et.TermInit
 */
export type TermInit = Message<"et.TermInit"> & {
  /**
   * @generated from field: repeated string environmentnames = 1;
   */
  environmentnames: string[];

  /**
   * @generated from field: repeated string environmentvalues = 2;
   */
  environmentvalues: string[];
};

/**
 * Describes the message et.TermInit.
 * Use `create(TermInitSchema)` to create a new message.
 */
export const TermInitSchema: GenMessage<TermInit> = /*@__PURE__*/
  messageDesc(file_ETerminal, 10);

/**
 * @generated from message et.TerminalUserInfo
 */
export type TerminalUserInfo = Message<"et.TerminalUserInfo"> & {
  /**
   * @generated from field: optional string id = 1;
   */
  id: string;

  /**
   * @generated from field: optional string passkey = 2;
   */
  passkey: string;

  /**
   * @generated from field: optional int64 uid = 3;
   */
  uid: bigint;

  /**
   * @generated from field: optional int64 gid = 4;
   */
  gid: bigint;

  /**
   * @generated from field: optional int64 fd = 5;
   */
  fd: bigint;
};

/**
 * Describes the message et.TerminalUserInfo.
 * Use `create(TerminalUserInfoSchema)` to create a new message.
 */
export const TerminalUserInfoSchema: GenMessage<TerminalUserInfo> = /*@__PURE__*/
  messageDesc(file_ETerminal, 11);

/**
 * @generated from enum et.TerminalPacketType
 */
export enum TerminalPacketType {
  /**
   * @generated from enum value: KEEP_ALIVE = 0;
   */
  KEEP_ALIVE = 0,

  /**
   * @generated from enum value: TERMINAL_BUFFER = 1;
   */
  TERMINAL_BUFFER = 1,

  /**
   * @generated from enum value: TERMINAL_INFO = 2;
   */
  TERMINAL_INFO = 2,

  /**
   * @generated from enum value: PORT_FORWARD_DESTINATION_REQUEST = 5;
   */
  PORT_FORWARD_DESTINATION_REQUEST = 5,

  /**
   * @generated from enum value: PORT_FORWARD_DESTINATION_RESPONSE = 6;
   */
  PORT_FORWARD_DESTINATION_RESPONSE = 6,

  /**
   * @generated from enum value: PORT_FORWARD_DATA = 7;
   */
  PORT_FORWARD_DATA = 7,

  /**
   * @generated from enum value: TERMINAL_USER_INFO = 8;
   */
  TERMINAL_USER_INFO = 8,

  /**
   * @generated from enum value: TERMINAL_INIT = 9;
   */
  TERMINAL_INIT = 9,

  /**
   * @generated from enum value: JUMPHOST_INIT = 10;
   */
  JUMPHOST_INIT = 10,
}

/**
 * Describes the enum et.TerminalPacketType.
 */
export const TerminalPacketTypeSchema: GenEnum<TerminalPacketType> = /*@__PURE__*/
  enumDesc(file_ETerminal, 0);
